### ISSUE TITLE
Otter.py Yv

### ISSUE THREAD

**Issue by CowboyTime** [cybergalactic/PythonVehicleSimulator#12]
Damping term Yv = 0, should be -M[1,1]/T_sway = -M[1,1] per Otter.m

**Comment by cybergalactic** [comment]
The Yv term improves damping at lower speeds and can be included with the crossflow drag term in yaw. I have updated the otter.py file to include linear damping and made other minor changes so that it complies with the Matlab version in the MSS toolbox. Generally, the linear and nonlinear damping terms must be tuned or estimated using time series from sea trials. The numerical values for linear damping in the otter.py file are based on engineering judgment.
