### ISSUE TITLE
Package request fail

### ISSUE THREAD

**Issue by GarbageGenerator** [cybergalactic/PythonVehicleSimulator#4]
When I run 'main.py',there is a error ' No module named 'python_vehicle_simulator' '
But I have use the command 'pip install <path>'
When I check the packages,I found the package 'python_vehicle_simulator' is 'request fail'

**Comment by cybergalactic** [comment]
As described in the Readme file you must run

    python3 -m pip install /MY_PATH/PythonVehicleSimulator-master

where you use the catalog name of the Python files and not the name "python_vehicle_simulator" when installing with pip.

**Comment by GarbageGenerator** [comment]
Thanks a lot for the prompt reply. And I'm excited to hear from you, you've accomplished a lot in this Academic Field!
I tried many times, but couldn't succeed.This is my code:

_`python3 -m pip install /D:\Post_graduate\Fossen_six_freedom\PythonVehicleSimulator-master/PythonVehicleSimulator-master`_

I'm sorry to bother you with such a small problem, thank you!

**Comment by cybergalactic** [comment]
This has been tested on  Linux and OSX. On my Mac  I use the command:

   python3 -m pip install -e /Users/thor/Documents/GitHub/PythonVehicleSimulator  

The downloaded files under the catalog PythonVehicleSimulator  are:
  LICENSE
  pyproject.toml
  src
  README.md
  setup.cfg
  tests

Maybe this is a Windows problem. Using the Windows Subsystem (WSL) might fail when the project path has space or a dash in the names.

**Comment by GarbageGenerator** [comment]
Thank you again. Once again, I've changed the system and tried again with linux, but I have a new problem.
I got an error while executing the following code
I didn't do cloning, is that the problem?
[code.txt](https://github.com/cybergalactic/PythonVehicleSimulator/files/9232698/code.txt)

**Comment by cybergalactic** [comment]
According to the error your “user" do not have write access to the catalogue /usr/local/lib/python3.10/dist-packages/
Try to install the package as root by using the command sudo, that is

sudo python3 -m pip install -e /media/ly/workspace/Fossen/PythonVehicleSimulator-master

----

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages/test-easy-install-33681.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.10/dist-packages/

Perhaps your account does not have write access to this directory?



On 1 Aug 2022, at 11:34, GarbageGenerator ***@***.******@***.***>> wrote:



Thank you again. Once again, I've changed the system and tried again with linux, but I have a new problem.
I got an error while executing the following code
I didn't do cloning, is that the problem?

***@***.***:/media/ly/workspace/Fossen/PythonVehicleSimulator-master$ python3 -m pip install -e /media/ly/workspace/Fossen/PythonVehicleSimulator-master
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///media/ly/workspace/Fossen/PythonVehicleSimulator-master
Installing build dependencies ... done
Checking if build backend supports build_editable ... done
Getting requirements to build wheel ... done
Installing backend dependencies ... done
Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /home/ly/.local/lib/python3.10/site-packages (from python-vehicle-simulator==1.0.1) (1.23.1)
Requirement already satisfied: matplotlib in /home/ly/.local/lib/python3.10/site-packages (from python-vehicle-simulator==1.0.1) (3.5.2)
Requirement already satisfied: pytest in /home/ly/.local/lib/python3.10/site-packages (from python-vehicle-simulator==1.0.1) (7.1.2)
Requirement already satisfied: cycler>=0.10 in /home/ly/.local/lib/python3.10/site-packages (from matplotlib->python-vehicle-simulator==1.0.1) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/ly/.local/lib/python3.10/site-packages (from matplotlib->python-vehicle-simulator==1.0.1) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in /home/ly/.local/lib/python3.10/site-packages (from matplotlib->python-vehicle-simulator==1.0.1) (4.34.4)
Requirement already satisfied: packaging>=20.0 in /home/ly/.local/lib/python3.10/site-packages (from matplotlib->python-vehicle-simulator==1.0.1) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3/dist-packages (from matplotlib->python-vehicle-simulator==1.0.1) (2.8.1)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib->python-vehicle-simulator==1.0.1) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib->python-vehicle-simulator==1.0.1) (9.0.1)
Requirement already satisfied: iniconfig in /home/ly/.local/lib/python3.10/site-packages (from pytest->python-vehicle-simulator==1.0.1) (1.1.1)
Requirement already satisfied: tomli>=1.0.0 in /home/ly/.local/lib/python3.10/site-packages (from pytest->python-vehicle-simulator==1.0.1) (2.0.1)
Requirement already satisfied: attrs>=19.2.0 in /home/ly/.local/lib/python3.10/site-packages (from pytest->python-vehicle-simulator==1.0.1) (22.1.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /home/ly/.local/lib/python3.10/site-packages (from pytest->python-vehicle-simulator==1.0.1) (1.0.0)
Requirement already satisfied: py>=1.8.2 in /home/ly/.local/lib/python3.10/site-packages (from pytest->python-vehicle-simulator==1.0.1) (1.11.0)
Installing collected packages: python-vehicle-simulator
Running setup.py develop for python-vehicle-simulator
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [32 lines of output]
    running develop
    /usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    WARNING: The user site-packages directory is disabled.
    /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    error: can't create or remove files in install directory

    The following error occurred while trying to add or remove files in the
    installation directory:

        [Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages/test-easy-install-33681.write-test'

    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:

        /usr/local/lib/python3.10/dist-packages/

    Perhaps your account does not have write access to this directory?  If the
    installation directory is a system-owned directory, you may need to sign in
    as the administrator or "root" account.  If you do not have administrative
    access to this machine, you may wish to choose a different installation
    directory, preferably one that is listed in your PYTHONPATH environment
    variable.

    For information on other options, you may wish to consult the
    documentation at:

      https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

    Please make the appropriate changes for your system and try again.

    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.


error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [32 lines of output]
running develop
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
warnings.warn(
WARNING: The user site-packages directory is disabled.
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
warnings.warn(
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages/test-easy-install-33681.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.10/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.

[end of output]


note: This error originates from a subprocess, and is likely not a problem with pip.`
